name: Security Scanning Pipeline

on:
  workflow_dispatch:
    inputs:
      file_name:
        required: true
        type: string
        description: "Input file name"
      command:
        required: true
        type: string
        description: "Command to execute (cat filename will be auto-handled)"
      notify_mode:
        required: false
        type: choice
        default: "line"
        description: "Notification mode (line = line by line, bulk = full file)"
        options:
          - line
          - bulk

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: ~/tools
          key: pdtools-v1-${{ runner.os }}
          
      - name: Install security tools
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          echo "[*] Installing ProjectDiscovery tools (not cached)..."
          mkdir -p ~/tools
          
          # Download pre-compiled binaries (faster than go install)
          echo "[*] Downloading subfinder..."
          wget -q https://github.com/projectdiscovery/subfinder/releases/latest/download/subfinder_2.8.0_linux_amd64.zip
          unzip -o -q subfinder_2.8.0_linux_amd64.zip
          mv subfinder ~/tools/
          
          echo "[*] Downloading httpx..."
          wget -q https://github.com/projectdiscovery/httpx/releases/latest/download/httpx_1.7.1_linux_amd64.zip
          unzip -o -q httpx_1.7.1_linux_amd64.zip
          mv httpx ~/tools/
          
          echo "[*] Downloading nuclei..."
          wget -q https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_3.4.10_linux_amd64.zip
          unzip -o -q nuclei_3.4.10_linux_amd64.zip
          mv nuclei ~/tools/
          
          echo "[*] Downloading notify..."
          wget -q https://github.com/projectdiscovery/notify/releases/latest/download/notify_1.0.7_linux_amd64.zip
          unzip -o -q notify_1.0.7_linux_amd64.zip
          mv notify ~/tools/

          echo "[*] Downloading katana..."
          wget -q https://github.com/projectdiscovery/katana/releases/latest/download/katana_1.2.1_linux_amd64.zip
          unzip -o -q katana_1.2.1_linux_amd64.zip
          mv katana ~/tools/
          
          chmod +x ~/tools/*
          echo "[+] Tools downloaded successfully"
          
      - name: Setup tool paths
        run: |
          echo "$HOME/tools" >> $GITHUB_PATH
          
          echo "[*] Verifying tool installations..."
          ~/tools/subfinder -version || echo "subfinder not found"
          ~/tools/httpx -version || echo "httpx not found" 
          ~/tools/nuclei -version || echo "nuclei not found"
          ~/tools/notify -version || echo "notify not found"
          ~/tools/katana -version || echo "katana not found"
          
      - name: Cache nuclei templates
        id: cache-templates
        uses: actions/cache@v3
        with:
          path: nuclei-templates
          key: nuclei-templates-${{ github.run_id }}
          restore-keys: nuclei-templates-
          
      - name: Clone nuclei templates
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: |
          echo "[*] Cloning nuclei templates..."
          git clone --depth 1 https://github.com/projectdiscovery/nuclei-templates.git
          echo "[+] Templates cloned"
          
      - name: Create notify credentials file
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "[*] Creating temporary notify credentials file..."
          cat > temp_creds.yml << EOF
          telegram:
            - id: "tel"
              telegram_api_key: "$TELEGRAM_API_KEY"
              telegram_chat_id: "$TELEGRAM_CHAT_ID"
              telegram_format: "{{data}}"
              telegram_parsemode: "Markdown"
          EOF
          echo "[+] Temporary credentials file created"
          
      - name: Verify input file exists
        run: |
          if [ ! -f "upload/${{ inputs.file_name }}" ]; then
            echo "[!] Input file upload/${{ inputs.file_name }} not found in repository"
            echo "[*] Available files in upload directory:"
            ls -la upload/ || echo "Upload directory doesn't exist"
            exit 1
          fi
          echo "[+] Input file upload/${{ inputs.file_name }} found"
          echo "[*] File size: $(wc -l < upload/${{ inputs.file_name }}) lines"
          
      - name: Execute scanning pipeline
        run: |
          echo "[*] Building pipeline..."
          echo "[*] Input file: upload/${{ inputs.file_name }}"
          echo "[*] Command: ${{ inputs.command }}"
          echo "[*] Notify mode: ${{ inputs.notify_mode }}"
          
          RESULT_FILE="pipeline_results.txt"
          
          # Run the main pipeline
          if eval "cat upload/${{ inputs.file_name }} | ${{ inputs.command }} > $RESULT_FILE"; then
            echo "[+] Pipeline executed successfully"
          else
            echo "[!] Pipeline failed with exit code $?"
            echo "❌ Scanning failed for upload/${{ inputs.file_name }}" | notify -pc temp_creds.yml -silent || true
            exit 1
          fi
          
          # Handle notification modes
          if [ "${{ inputs.notify_mode }}" = "bulk" ]; then
            echo "[*] Sending bulk notification..."
            notify -pc temp_creds.yml -silent -data $RESULT_FILE || true
          else
            echo "[*] Sending line-by-line notification..."
            cat $RESULT_FILE | notify -pc temp_creds.yml -silent || true
          fi
          
          echo "[+] Notifications sent"
          
      - name: Cleanup
        if: always()
        run: |
          rm -f temp_creds.yml pipeline_results.txt
          rm -rf nuclei-templates
          echo "[+] Cleanup completed"
